version: '3.6'

services:
  frontend:
    restart: always
    image: "frontend/baseapp:2.6.0"
    volumes:
      - ../config/frontend/env.js:/usr/share/nginx/html/config/env.js
    labels:
      - "traefik.http.routers.frontend-ftb.rule=Host(`tst.algo-trading-machine.com`) && PathPrefix(`/`)"
      - "traefik.enable=true"
      - "traefik.http.services.frontend-ftb.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend-ftb.entrypoints=websecure"
      - "traefik.http.routers.frontend-ftb.tls=true"
      - "traefik.http.routers.frontend-ftb.tls.certresolver=myresolver"

  tower:
    restart: always
    image: "quay.io/openware/tower:2.6.36"
    volumes:
      - ../config/frontend/tower.js:/home/app/env.js
    labels:
      - "traefik.http.routers.tower-ftb.rule=Host(`tst.algo-trading-machine.com`) && PathPrefix(`/tower`)"
      - "traefik.enable=true"
      - "traefik.http.services.tower-ftb.loadbalancer.server.port=8080"
      - "traefik.http.routers.tower-ftb.entrypoints=websecure"
      - "traefik.http.routers.tower-ftb.tls=true"
      - "traefik.http.routers.tower-ftb.tls.certresolver=myresolver"
