version: '3.6'

services:
  superset:
    image: "amancevice/superset:0.28.1"
    restart: always
    volumes:
      - superset_db:/var/lib/superset
    labels:
      - "traefik.http.routers.superset-ftb.rule=Host(`superset.algo-trading-machine.com`)"
      - "traefik.http.services.superset-ftb.loadbalancer.server.port=8088"
      - "traefik.enable=true"
      - "traefik.http.routers.superset-ftb.entrypoints=websecure"

volumes:
  superset_db:
